module.exports = [
<<<<<<< HEAD
  { name: 'Bibimbap' },
  { name: 'Breakfast Sandwiches' },
  { name: 'Catering' },
  { name: 'Coconut Oil Fried Rice' },
  { name: 'Coffee & Tea' },
  { name: 'Fresh Juice' },
  { name: 'Healthy Plates' },
  { name: 'Healthy Shots' },
  { name: 'Incredibowls' },
  { name: 'Juice Cleanse' },
  { name: 'Miscellaneous' },
  { name: 'Salad' },
  { name: 'Smoothies' },
  { name: 'Soup' },
  { name: 'Vegan Tacos' },
=======
	{ name: 'Bibimbap' },
	{ name: 'Breakfast Sandwiches' },
	{ name: 'Catering' },
	{ name: 'Coconut Oil Fried Rice' },
	{ name: 'Coffee & Tea' },
	{ name: 'Fresh Juice' },
	{ name: 'Healthy Plates' },
	{ name: 'Healthy Shots' },
	{ name: 'Incredibowls' },
	{ name: 'Juice Cleanse' },
	{ name: 'Miscellaneous' },
	{ name: 'Salad' },
	{ name: 'Smoothies' },
	{ name: 'Soup' },
	{ name: 'Vegan Tacos' }
>>>>>>> 18896b3d9a620c63496df4a0679489c7cd0bfc85
];
