/* eslint-disable max-len */
/* eslint-disable quotes */
module.exports = [
  {
    productName: 'Arugula Bi Bim Bap',
    variationName: 'Regular',
    inventory: 5,
    price: 9.5,
  },
  {
    productName: 'Bi Bim Bap',
    variationName: 'Regular',
    inventory: 10,
    price: 8.5,
  },
  {
    productName: 'Chicken Mushroom Bi Bim Bap',
    variationName: 'Regular',
    inventory: 20,
    price: 14.0,
  },
  {
    productName: 'Grilled Tofu Mushroom Bi Bim Bap',
    variationName: 'Regular',
    inventory: 10,
    price: 14.0,
  },
  {
    productName: 'Kimchi Bi Bim Bap',
    variationName: 'Regular',
    inventory: 10,
    price: 10.5,
  },
  {
    productName: 'Mushroom Bi Bim Bap',
    variationName: 'Regular',
    inventory: 10,
    price: 10.5,
  },
  {
    productName: 'Roll with Butter',
    variationName: 'Regular',
    inventory: 10,
    price: 2.0,
  },
  {
    productName: 'Roll With Egg',
    variationName: 'Regular',
    inventory: 10,
    price: 3.5,
  },
  {
    productName: 'Roll With Egg And Cheese',
    variationName: 'Regular',
    inventory: 10,
    price: 3.8,
  },
  {
    productName: 'Roll With Egg White',
    variationName: 'Regular',
    inventory: 10,
    price: 4.0,
  },
  {
    productName: 'Roll With Jam',
    variationName: 'Regular',
    inventory: 10,
    price: 2.0,
  },
  {
    productName: 'Roll With Peanut Butter',
    variationName: 'Regular',
    inventory: 10,
    price: 2.3,
  },
  {
    productName: 'Bi Bim Bap Tray',
    variationName: 'Regular',
    inventory: 10,
    price: 70.0,
  },
  {
    productName: 'Dumpling Tray',
    variationName: 'Regular',
    inventory: 10,
    price: 40.0,
  },
  {
    productName: 'Salad Tray',
    variationName: 'Regular',
    inventory: 10,
    price: 45.0,
  },
  {
    productName: 'Kimchi Coconut Oil Fried Rice',
    variationName: 'Regular',
    inventory: 10,
    price: 10.5,
  },
  {
    productName: 'Mango Coconut Oil Fried Rice',
    variationName: 'Regular',
    inventory: 10,
    price: 9.0,
  },
  {
    productName: 'Pineapple Coconut Oil Fried Rice',
    variationName: 'Regular',
    inventory: 10,
    price: 9.0,
  },
  {
    productName: 'Hot Coffee',
    variationName: 'Small',
    inventory: 10,
    price: 1.5,
  },
  {
    productName: 'Hot Coffee',
    variationName: 'Medium',
    inventory: 10,
    price: 2.0,
  },
  {
    productName: 'Hot Coffee',
    variationName: 'Large',
    inventory: 10,
    price: 2.3,
  },
  {
    productName: 'Hot Tea',
    variationName: 'Small',
    inventory: 10,
    price: 1.5,
  },
  {
    productName: 'Hot Tea',
    variationName: 'Medium',
    inventory: 10,
    price: 2.0,
  },
  {
    productName: 'Hot Tea',
    variationName: 'Large',
    inventory: 10,
    price: 2.3,
  },
  {
    productName: 'ICE Coffee',
    variationName: 'Small',
    inventory: 10,
    price: 1.5,
  },
  {
    productName: 'ICE Coffee',
    variationName: 'Medium',
    inventory: 10,
    price: 2.0,
  },
  {
    productName: 'ICE Coffee',
    variationName: 'Large',
    inventory: 10,
    price: 2.3,
  },
  {
    productName: 'Turmeric Tea',
    variationName: 'Regular',
    inventory: 10,
    price: 4.0,
  },
  {
    productName: 'ABC',
    variationName: '8oz',
    inventory: 10,
    price: 4.3,
  },
  {
    productName: 'ABC',
    variationName: '12oz',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: 'ABC',
    variationName: '16oz',
    inventory: 10,
    price: 8.0,
  },
  {
    productName: 'ABC',
    variationName: '24oz',
    inventory: 10,
    price: 11.0,
  },
  {
    productName: "Doc's Prescription",
    variationName: '8oz',
    inventory: 10,
    price: 4.3,
  },
  {
    productName: "Doc's Prescription",
    variationName: '12oz',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: "Doc's Prescription",
    variationName: '16oz',
    inventory: 10,
    price: 8.0,
    category: 'Fresh Juice',
  },
  {
    productName: "Doc's Prescription",
    variationName: '24oz',
    inventory: 10,
    price: 11.0,
  },
  {
    productName: 'Hulk Blood',
    variationName: '8oz',
    inventory: 10,
    price: 4.3,
  },
  {
    productName: 'Hulk Blood',
    variationName: '12oz',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: 'Hulk Blood',
    variationName: '16oz',
    inventory: 10,
    price: 8.0,
  },
  {
    productName: 'Hulk Blood',
    variationName: '24oz',
    inventory: 10,
    price: 11.0,
  },
  // {
  //   productName: 'Jealousy',
  //   variationName: '12oz',
  //   inventory: 10,
  //   price: 8.0,
  // },
  // {
  //   productName: 'Jealousy',
  //   variationName: '16oz',
  //   inventory: 10,
  //   price: 10.0,
  // },
  // {
  //   productName: 'Jealousy',
  //   variationName: '24oz',
  //   inventory: 10,
  //   price: 13.0,
  // },
  {
    productName: 'Lemon Ginger Zinger',
    variationName: '8oz',
    inventory: 10,
    price: 4.3,
  },
  {
    productName: 'Lemon Ginger Zinger',
    variationName: '12oz',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: 'Lemon Ginger Zinger',
    variationName: '16oz',
    inventory: 10,
    price: 8.0,
  },
  {
    productName: 'Lemon Ginger Zinger',
    variationName: '24oz',
    inventory: 10,
    price: 11.0,
  },
  {
    productName: 'Pina Colada',
    variationName: '8oz',
    inventory: 10,
    price: 4.3,
  },
  {
    productName: 'Pina Colada',
    variationName: '12oz',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: 'Pina Colada',
    variationName: '16oz',
    inventory: 10,
    price: 8.0,
  },
  {
    productName: 'Pina Colada',
    variationName: '24oz',
    inventory: 10,
    price: 11.0,
  },
  {
    productName: 'Pink Panther',
    variationName: '8oz',
    inventory: 10,
    price: 4.3,
  },
  {
    productName: 'Pink Panther',
    variationName: '12oz',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: 'Pink Panther',
    variationName: '16oz',
    inventory: 10,
    price: 8.0,
  },
  {
    productName: 'Pink Panther',
    variationName: '24oz',
    inventory: 10,
    price: 11.0,
  },
  {
    productName: 'Rejuvenation',
    variationName: '8oz',
    inventory: 10,
    price: 4.3,
  },
  {
    productName: 'Rejuvenation',
    variationName: '12oz',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: 'Rejuvenation',
    variationName: '16oz',
    inventory: 10,
    price: 8.0,
  },
  {
    productName: 'Rejuvenation',
    variationName: '24oz',
    inventory: 10,
    price: 11.0,
  },
  {
    productName: 'Sun Kissed',
    variationName: '8oz',
    inventory: 10,
    price: 4.3,
  },
  {
    productName: 'Sun Kissed',
    variationName: '12oz',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: 'Sun Kissed',
    variationName: '16oz',
    inventory: 10,
    price: 8.0,
  },
  {
    productName: 'Sun Kissed',
    variationName: '24oz',
    inventory: 10,
    price: 11.0,
  },
  {
    productName: 'Tropical Breeze',
    variationName: '8oz',
    inventory: 10,
    price: 4.3,
  },
  {
    productName: 'Tropical Breeze',
    variationName: '12oz',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: 'Tropical Breeze',
    variationName: '16oz',
    inventory: 10,
    price: 8.0,
  },
  {
    productName: 'Tropical Breeze',
    variationName: '24oz',
    inventory: 10,
    price: 11.0,
  },
  {
    productName: 'Virus Kryptonite',
    variationName: '8oz',
    inventory: 10,
    price: 4.3,
  },
  {
    productName: 'Virus Kryptonite',
    variationName: '12oz',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: 'Virus Kryptonite',
    variationName: '16oz',
    inventory: 10,
    price: 8.0,
  },
  {
    productName: 'Virus Kryptonite',
    variationName: '24oz',
    inventory: 10,
    price: 11.0,
  },
  {
    productName: 'Wonder Woman',
    variationName: '8oz',
    inventory: 10,
    price: 5.6,
  },
  {
    productName: 'Wonder Woman',
    variationName: '12oz',
    inventory: 10,
    price: 8.0,
  },
  {
    productName: 'Wonder Woman',
    variationName: '16oz',
    inventory: 10,
    price: 10.0,
  },
  {
    productName: 'Wonder Woman',
    variationName: '24oz',
    inventory: 10,
    price: 13.0,
  },
  {
    productName: 'Avocado Chorizo Sandwich',
    variationName: 'Regular',
    inventory: 10,
    price: 8.3,
  },
  {
    productName: 'Mumbai Veggie Patties',
    variationName: 'Regular',
    inventory: 10,
    price: 6.5,
  },
  {
    productName: 'Portobello Kimchi Burger',
    variationName: 'Regular',
    inventory: 10,
    price: 7.5,
    category: 'Healthy Plates',
  },
  {
    productName: 'Samosa',
    variationName: 'Regular',
    inventory: 10,
    price: 6.5,
  },
  {
    productName: 'Spicy Avocado Egg Sandwich',
    variationName: 'Regular',
    inventory: 10,
    price: 6.5,
  },
  {
    productName: 'Spicy Chorizo Egg Sandwich',
    variationName: 'Regular',
    inventory: 10,
    price: 6.5,
  },
  {
    productName: 'Veggie Momos',
    variationName: 'Regular',
    inventory: 10,
    price: 6.5,
  },
  {
    productName: 'Aloe-Ha',
    variationName: 'Regular',
    inventory: 10,
    price: 3.25,
  },
  {
    productName: 'Amino Acid',
    variationName: 'Regular',
    inventory: 10,
    price: 3.25,
  },
  {
    productName: 'AVCG',
    variationName: 'Regular',
    inventory: 10,
    price: 3.25,
  },
  {
    productName: 'Beet It',
    variationName: 'Regular',
    inventory: 10,
    price: 2.75,
  },
  {
    productName: 'Black Beauty',
    variationName: 'Regular',
    inventory: 10,
    price: 3.25,
  },
  {
    productName: 'Celery Shot',
    variationName: 'Regular',
    inventory: 10,
    price: 2.75,
  },
  {
    productName: 'Double Shot Of Sunshine',
    variationName: 'Regular',
    inventory: 10,
    price: 3.25,
  },
  {
    productName: 'Fire Ball',
    variationName: 'Regular',
    inventory: 10,
    price: 3.25,
  },
  {
    productName: "Gandhi's Cure",
    variationName: 'Regular',
    inventory: 10,
    price: 3.25,
  },
  {
    productName: 'Ginger shot',
    variationName: 'Regular',
    inventory: 10,
    price: 2.75,
  },
  {
    productName: 'Iron Man',
    variationName: 'Regular',
    inventory: 10,
    price: 3.25,
  },
  {
    productName: 'Liver Detoxifier',
    variationName: 'Regular',
    inventory: 10,
    price: 3.25,
  },
  {
    productName: 'Mean Green',
    variationName: 'Regular',
    inventory: 10,
    price: 3.25,
  },
  {
    productName: 'Meera’s Devotion',
    variationName: 'Regular',
    inventory: 10,
    price: 3.25,
  },
  {
    productName: 'Osaka Shot',
    variationName: 'Regular',
    inventory: 10,
    price: 3.25,
  },
  {
    productName: 'Spirulina Shot',
    variationName: 'Regular',
    inventory: 10,
    price: 3.25,
  },
  {
    productName: 'Type 2',
    variationName: 'Regular',
    inventory: 10,
    price: 3.25,
  },
  {
    productName: 'Autumn Bowl',
    variationName: 'Regular',
    inventory: 10,
    price: 10.5,
  },
  {
    productName: 'Berry-licious',
    variationName: 'Regular',
    inventory: 10,
    price: 10.5,
  },
  {
    productName: 'Hulk Bowl',
    variationName: 'Regular',
    inventory: 10,
    price: 10.5,
  },
  {
    productName: 'Princess',
    variationName: 'Regular',
    inventory: 10,
    price: 10.5,
  },
  {
    productName: '1 Day',
    variationName: '8oz',
    inventory: 10,
    price: 12.51,
  },
  {
    productName: '1 Day',
    variationName: '12oz',
    inventory: 10,
    price: 17.46,
  },
  {
    productName: '1 Day',
    variationName: '16oz',
    inventory: 10,
    price: 23.28,
  },
  {
    productName: '1 Day',
    variationName: '24oz',
    inventory: 10,
    price: 32.01,
  },
  {
    productName: '1 day + shots',
    variationName: '8oz',
    inventory: 10,
    price: 17.66,
  },
  {
    productName: '1 day + shots',
    variationName: '12oz',
    inventory: 10,
    price: 22.56,
  },
  {
    productName: '1 day + shots',
    variationName: '16oz',
    inventory: 10,
    price: 28.32,
  },
  {
    productName: '1 day + shots',
    variationName: '24oz',
    inventory: 10,
    price: 36.96,
  },
  {
    productName: '3 days',
    variationName: '8oz',
    inventory: 10,
    price: 36.77,
  },
  {
    productName: '3 days',
    variationName: '12oz',
    inventory: 10,
    price: 51.3,
  },
  {
    productName: '3 days',
    variationName: '16oz',
    inventory: 10,
    price: 68.4,
  },
  {
    productName: '3 days',
    variationName: '24oz',
    inventory: 10,
    price: 94.05,
  },
  {
    productName: '3 days + shots',
    variationName: '8oz',
    inventory: 10,
    price: 51.89,
  },
  {
    productName: '3 days + shots',
    variationName: '12oz',
    inventory: 10,
    price: 66.27,
  },
  {
    productName: '3 days + shots',
    variationName: '16oz',
    inventory: 10,
    price: 83.19,
  },
  {
    productName: '3 days + shots',
    variationName: '24oz',
    inventory: 10,
    price: 108.57,
  },
  {
    productName: '5 days',
    variationName: '8oz',
    inventory: 10,
    price: 59.99,
  },
  {
    productName: '5 days',
    variationName: '12oz',
    inventory: 10,
    price: 83.7,
  },
  {
    productName: '5 days',
    variationName: '16oz',
    inventory: 10,
    price: 111.6,
  },
  {
    productName: '5 days',
    variationName: '24oz',
    inventory: 10,
    price: 153.45,
  },
  {
    productName: '5 days + shots',
    variationName: '8oz',
    inventory: 10,
    price: 84.64,
  },
  {
    productName: '5 days + shots',
    variationName: '12oz',
    inventory: 10,
    price: 108.1,
  },
  {
    productName: '5 days + shots',
    variationName: '16oz',
    inventory: 10,
    price: 135.7,
  },
  {
    productName: '5 days + shots',
    variationName: '24oz',
    inventory: 10,
    price: 177.1,
  },
  {
    productName: 'Clif Bar',
    variationName: 'Regular',
    inventory: 10,
    price: 2.5,
  },
  {
    productName: 'Coconut Bites',
    variationName: 'Regular',
    inventory: 10,
    price: 0.6,
  },
  {
    productName: 'Ferrero Rocher',
    variationName: 'Regular',
    inventory: 10,
    price: 0.25,
  },
  {
    productName: 'Kind Bar',
    variationName: 'Large',
    inventory: 10,
    price: 2.5,
  },
  {
    productName: 'Poland Spring Water',
    variationName: 'Regular',
    inventory: 10,
    price: 1.0,
  },
  {
    productName: 'Rice Krispies',
    variationName: 'Regular',
    inventory: 10,
    price: 2.0,
  },
  {
    productName: 'Sea Weed',
    variationName: 'Regular',
    inventory: 10,
    price: 2.0,
  },
  {
    productName: 'Z Bar',
    variationName: 'Regular',
    inventory: 10,
    price: 2.0,
  },
  {
    productName: 'Delish Quinoa salad',
    variationName: 'Regular',
    inventory: 10,
    price: 8.5,
  },
  {
    productName: 'Tofu Chorizo Salad',
    variationName: 'Regular',
    inventory: 10,
    price: 9.0,
  },
  {
    productName: 'Berry Excited',
    variationName: '16oz',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: 'Berry Excited',
    variationName: '20oz',
    inventory: 10,
    price: 8.0,
  },
  {
    productName: 'Chunky Monkey',
    variationName: '16oz',
    inventory: 10,
    price: 7.0,
  },
  {
    productName: 'Chunky Monkey',
    variationName: '20oz',
    inventory: 10,
    price: 9.0,
  },
  {
    productName: "Einstein's Brain",
    variationName: '16oz',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: "Einstein's Brain",
    variationName: '20oz',
    inventory: 10,
    price: 8.0,
  },
  {
    productName: 'Green Breakfast',
    variationName: '16oz',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: 'Green Breakfast',
    variationName: '20oz',
    inventory: 10,
    price: 8.0,
  },
  {
    productName: 'Hercules',
    variationName: '16oz',
    inventory: 10,
    price: 7.0,
  },
  {
    productName: 'Hercules',
    variationName: '20oz',
    inventory: 10,
    price: 9.0,
  },
  {
    productName: "Kale'EM",
    variationName: '16oz',
    inventory: 10,
    price: 7.0,
  },
  {
    productName: "Kale'EM",
    variationName: '20oz',
    inventory: 10,
    price: 9.0,
  },
  {
    productName: 'Nutz 4 Pumpkin',
    variationName: '16oz',
    inventory: 10,
    price: 7.0,
  },
  {
    productName: 'Nutz 4 Pumpkin',
    variationName: '20oz',
    inventory: 10,
    price: 9.0,
  },
  {
    productName: 'Osaka',
    variationName: '16oz',
    inventory: 10,
    price: 7.0,
  },
  {
    productName: 'Osaka',
    variationName: '20oz',
    inventory: 10,
    price: 9.0,
  },
  {
    productName: 'St.Mango',
    variationName: '16oz',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: 'St.Mango',
    variationName: '20oz',
    inventory: 10,
    price: 8.0,
  },
  {
    productName: 'Butternut Squash Soup',
    variationName: 'Regular',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: 'Lentil Soup',
    variationName: 'Regular',
    inventory: 10,
    price: 5.5,
  },
  {
    productName: 'Spinach Soup',
    variationName: 'Regular',
    inventory: 10,
    price: 5.5,
  },
  {
    productName: 'Emily',
    variationName: 'Regular',
    inventory: 10,
    price: 5.0,
  },
  {
    productName: 'Jacob',
    variationName: 'Regular',
    inventory: 10,
    price: 5.0,
  },
  {
    productName: 'Joe',
    variationName: 'Regular',
    inventory: 10,
    price: 6.0,
  },
  {
    productName: 'Lauren',
    variationName: 'Regular',
    inventory: 10,
    price: 5.0,
  },
  {
    productName: 'Maria',
    variationName: 'Regular',
    inventory: 10,
    price: 5.0,
  },
  {
    productName: 'Sofia',
    variationName: 'Regular',
    inventory: 10,
    price: 5.0,
  },
];
