module.exports = [
  {
    title: 'Arugula Bi Bim Bap',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 9.5,
    category: 'Bibimbap',
  },
  {
    title: 'Bi Bim Bap',
    variationName: 'Regular',
    description:
      'Gluten Free  Brown Rice, carrot, Boston Lettuce, Soybean paste, sesame oil, coconut oil fried egg.',
    inventory: 10,
    price: 8.5,
    category: 'Bibimbap',
  },
  {
    title: 'Chicken Mushroom Bi Bim Bap',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 14.0,
    category: 'Bibimbap',
  },
  {
    title: 'Grilled Tofu Mushroom Bi Bim Bap',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 14.0,
    category: 'Bibimbap',
  },
  {
    title: 'Kimchi Bi Bim Bap',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 10.5,
    category: 'Bibimbap',
  },
  {
    title: 'Mushroom Bi Bim Bap',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 10.5,
    category: 'Bibimbap',
  },
  {
    title: 'Roll with Butter',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 2.0,
    category: 'Breakfast Sandwiches',
  },
  {
    title: 'Roll With Egg',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 3.5,
    category: 'Breakfast Sandwiches',
  },
  {
    title: 'Roll With Egg And Cheese',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 3.8,
    category: 'Breakfast Sandwiches',
  },
  {
    title: 'Roll With Egg White',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 4.0,
    category: 'Breakfast Sandwiches',
  },
  {
    title: 'Roll With Jam',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 2.0,
    category: 'Breakfast Sandwiches',
  },
  {
    title: 'Roll With Peanut Butter',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 2.3,
    category: 'Breakfast Sandwiches',
  },
  {
    title: 'Bi Bim Bap Tray',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 70.0,
    category: 'Catering',
  },
  {
    title: 'Dumpling Tray',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 40.0,
    category: 'Catering',
  },
  {
    title: 'Salad Tray',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 45.0,
    category: 'Catering',
  },
  {
    title: 'Kimchi Coconut Oil Fried Rice',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 10.5,
    category: 'Coconut Oil Fried Rice',
  },
  {
    title: 'Mango Coconut Oil Fried Rice',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 9.0,
    category: 'Coconut Oil Fried Rice',
  },
  {
    title: 'Pineapple Coconut Oil Fried Rice',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 9.0,
    category: 'Coconut Oil Fried Rice',
  },
  {
    title: 'Hot Coffee',
    variationName: 'Small',
    description: '',
    inventory: 10,
    price: 1.5,
    category: 'Coffee & Tea',
  },
  {
    title: 'Hot Coffee',
    variationName: 'Medium',
    description: '',
    inventory: 10,
    price: 2.0,
    category: 'Coffee & Tea',
  },
  {
    title: 'Hot Coffee',
    variationName: 'Large',
    description: '',
    inventory: 10,
    price: 2.3,
    category: 'Coffee & Tea',
  },
  {
    title: 'Hot Tea',
    variationName: 'Small',
    description: '',
    inventory: 10,
    price: 1.5,
    category: 'Coffee & Tea',
  },
  {
    title: 'Hot Tea',
    variationName: 'Medium',
    description: '',
    inventory: 10,
    price: 2.0,
    category: 'Coffee & Tea',
  },
  {
    title: 'Hot Tea',
    variationName: 'Large',
    description: '',
    inventory: 10,
    price: 2.3,
    category: 'Coffee & Tea',
  },
  {
    title: 'ICE Coffee',
    variationName: 'Small',
    description: '',
    inventory: 10,
    price: 1.5,
    category: 'Coffee & Tea',
  },
  {
    title: 'ICE Coffee',
    variationName: 'Medium',
    description: '',
    inventory: 10,
    price: 2.0,
    category: 'Coffee & Tea',
  },
  {
    title: 'ICE Coffee',
    variationName: 'Large',
    description: '',
    inventory: 10,
    price: 2.3,
    category: 'Coffee & Tea',
  },
  {
    title: 'Turmeric Tea',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 4.0,
    category: 'Coffee & Tea',
  },
  {
    title: 'ABC',
    variationName: '8oz',
    description: '',
    inventory: 10,
    price: 4.3,
    category: 'Fresh Juice',
  },
  {
    title: 'ABC',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 6.0,
    category: 'Fresh Juice',
  },
  {
    title: 'ABC',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Fresh Juice',
  },
  {
    title: 'ABC',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 11.0,
    category: 'Fresh Juice',
  },
  {
    title: "Doc's Prescription",
    variationName: '8oz',
    description: 'Celery Apple Ginger Lemon',
    inventory: 10,
    price: 4.3,
    category: 'Fresh Juice',
  },
  {
    title: "Doc's Prescription",
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 6.0,
    category: 'Fresh Juice',
  },
  {
    title: "Doc's Prescription",
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Fresh Juice',
  },
  {
    title: "Doc's Prescription",
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 11.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Hulk Blood',
    variationName: '8oz',
    description: 'Kale Apple Ginger Lemon',
    inventory: 10,
    price: 4.3,
    category: 'Fresh Juice',
  },
  {
    title: 'Hulk Blood',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 6.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Hulk Blood',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Hulk Blood',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 11.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Jealousy',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Jealousy',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 10.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Jealousy',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 13.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Lemon Ginger Zinger',
    variationName: '8oz',
    description: 'Carrot Apple Ginger Lemon',
    inventory: 10,
    price: 4.3,
    category: 'Fresh Juice',
  },
  {
    title: 'Lemon Ginger Zinger',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 6.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Lemon Ginger Zinger',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Lemon Ginger Zinger',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 11.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Pina Colada',
    variationName: '8oz',
    description: 'Pineapple Coconut Water',
    inventory: 10,
    price: 4.3,
    category: 'Fresh Juice',
  },
  {
    title: 'Pina Colada',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 6.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Pina Colada',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Pina Colada',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 11.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Pink Panther',
    variationName: '8oz',
    description: 'Watermelon Strawberry Apple Orange',
    inventory: 10,
    price: 4.3,
    category: 'Fresh Juice',
  },
  {
    title: 'Pink Panther',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 6.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Pink Panther',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Pink Panther',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 11.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Rejuvenation',
    variationName: '8oz',
    description: 'Cucumber Celery Apple Ginger',
    inventory: 10,
    price: 4.3,
    category: 'Fresh Juice',
  },
  {
    title: 'Rejuvenation',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 6.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Rejuvenation',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Rejuvenation',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 11.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Sun Kissed',
    variationName: '8oz',
    description: 'Pineapple Apple Ginger',
    inventory: 10,
    price: 4.3,
    category: 'Fresh Juice',
  },
  {
    title: 'Sun Kissed',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 6.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Sun Kissed',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Sun Kissed',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 11.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Tropical Breeze',
    variationName: '8oz',
    description: 'Pineapple Apple Orange',
    inventory: 10,
    price: 4.3,
    category: 'Fresh Juice',
  },
  {
    title: 'Tropical Breeze',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 6.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Tropical Breeze',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Tropical Breeze',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 11.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Virus Kryptonite',
    variationName: '8oz',
    description: 'Orange Lemon Grapefruit',
    inventory: 10,
    price: 4.3,
    category: 'Fresh Juice',
  },
  {
    title: 'Virus Kryptonite',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 6.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Virus Kryptonite',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Virus Kryptonite',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 11.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Wonder Woman',
    variationName: '8oz',
    description: 'Pomegranate Orange',
    inventory: 10,
    price: 5.6,
    category: 'Fresh Juice',
  },
  {
    title: 'Wonder Woman',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Wonder Woman',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 10.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Wonder Woman',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 13.0,
    category: 'Fresh Juice',
  },
  {
    title: 'Avocado Chorizo Sandwich',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 8.3,
    category: 'Healthy Plates',
  },
  {
    title: 'Mumbai Veggie Patties',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 6.5,
    category: 'Healthy Plates',
  },
  {
    title: 'Portobello Kimch Burger',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 7.5,
    category: 'Healthy Plates',
  },
  {
    title: 'Samosa',
    variationName: 'Regular',
    description: '2pcs',
    inventory: 10,
    price: 6.5,
    category: 'Healthy Plates',
  },
  {
    title: 'Spicy Avocado Egg Sandwich',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 6.5,
    category: 'Healthy Plates',
  },
  {
    title: 'Spicy Chorizo Egg Sandwich',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 6.5,
    category: 'Healthy Plates',
  },
  {
    title: 'Veggie Momos',
    variationName: 'Regular',
    description: '(5pcs)',
    inventory: 10,
    price: 6.5,
    category: 'Healthy Plates',
  },
  {
    title: 'Aloe-Ha',
    variationName: 'Regular',
    description: 'Aloe Lemon',
    inventory: 10,
    price: 3.25,
    category: 'Healthy Shots',
  },
  {
    title: 'Amino Acid',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 3.25,
    category: 'Healthy Shots',
  },
  {
    title: 'AVCG',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 3.25,
    category: 'Healthy Shots',
  },
  {
    title: 'Beet It',
    variationName: 'Regular',
    description: 'Pure Beet',
    inventory: 10,
    price: 2.75,
    category: 'Healthy Shots',
  },
  {
    title: 'Black Beauty',
    variationName: 'Regular',
    description: 'Activated charcoal, Lime, Coconut H2o',
    inventory: 10,
    price: 3.25,
    category: 'Healthy Shots',
  },
  {
    title: 'Celery Shot',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 2.75,
    category: 'Healthy Shots',
  },
  {
    title: 'Double Shot Of Sunshine',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 3.25,
    category: 'Healthy Shots',
  },
  {
    title: 'Fire Ball',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 3.25,
    category: 'Healthy Shots',
  },
  {
    title: "Gandhi's Cure",
    variationName: 'Regular',
    description: 'Tumeric Ginger Honey Almond Milk',
    inventory: 10,
    price: 3.25,
    category: 'Healthy Shots',
  },
  {
    title: 'Ginger shot',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 2.75,
    category: 'Healthy Shots',
  },
  {
    title: 'Iron Man',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 3.25,
    category: 'Healthy Shots',
  },
  {
    title: 'Liver Detoxifier',
    variationName: 'Regular',
    description: 'Cucumber Lemon & Milk Thistle',
    inventory: 10,
    price: 3.25,
    category: 'Healthy Shots',
  },
  {
    title: 'Mean Green',
    variationName: 'Regular',
    description: 'Wheatgrass & Almond Milk',
    inventory: 10,
    price: 3.25,
    category: 'Healthy Shots',
  },
  {
    title: 'Meera’s Devotion',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 3.25,
    category: 'Healthy Shots',
  },
  {
    title: 'Osaka Shot',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 3.25,
    category: 'Healthy Shots',
  },
  {
    title: 'Spirulina Shot',
    variationName: 'Regular',
    description: 'Spirulina, Alkaline water',
    inventory: 10,
    price: 3.25,
    category: 'Healthy Shots',
  },
  {
    title: 'Type 2',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 3.25,
    category: 'Healthy Shots',
  },
  {
    title: 'Autumn Bowl',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 10.5,
    category: 'Incredibowls',
  },
  {
    title: 'Berry-licious',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 10.5,
    category: 'Incredibowls',
  },
  {
    title: 'Hulk Bowl',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 10.5,
    category: 'Incredibowls',
  },
  {
    title: 'Princess',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 10.5,
    category: 'Incredibowls',
  },
  {
    title: '1 Day',
    variationName: '8oz',
    description: '3 juices',
    inventory: 10,
    price: 12.51,
    category: 'Juice Cleanse',
  },
  {
    title: '1 Day',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 17.46,
    category: 'Juice Cleanse',
  },
  {
    title: '1 Day',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 23.28,
    category: 'Juice Cleanse',
  },
  {
    title: '1 Day',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 32.01,
    category: 'Juice Cleanse',
  },
  {
    title: '1 day + shots',
    variationName: '8oz',
    description: '3 juices and 2 shots',
    inventory: 10,
    price: 17.66,
    category: 'Juice Cleanse',
  },
  {
    title: '1 day + shots',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 22.56,
    category: 'Juice Cleanse',
  },
  {
    title: '1 day + shots',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 28.32,
    category: 'Juice Cleanse',
  },
  {
    title: '1 day + shots',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 36.96,
    category: 'Juice Cleanse',
  },
  {
    title: '3 days',
    variationName: '8oz',
    description: '9 juices',
    inventory: 10,
    price: 36.77,
    category: 'Juice Cleanse',
  },
  {
    title: '3 days',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 51.3,
    category: 'Juice Cleanse',
  },
  {
    title: '3 days',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 68.4,
    category: 'Juice Cleanse',
  },
  {
    title: '3 days',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 94.05,
    category: 'Juice Cleanse',
  },
  {
    title: '3 days + shots',
    variationName: '8oz',
    description: '9 juices + 6 shots',
    inventory: 10,
    price: 51.89,
    category: 'Juice Cleanse',
  },
  {
    title: '3 days + shots',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 66.27,
    category: 'Juice Cleanse',
  },
  {
    title: '3 days + shots',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 83.19,
    category: 'Juice Cleanse',
  },
  {
    title: '3 days + shots',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 108.57,
    category: 'Juice Cleanse',
  },
  {
    title: '5 days',
    variationName: '8oz',
    description: '15 juices',
    inventory: 10,
    price: 59.99,
    category: 'Juice Cleanse',
  },
  {
    title: '5 days',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 83.7,
    category: 'Juice Cleanse',
  },
  {
    title: '5 days',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 111.6,
    category: 'Juice Cleanse',
  },
  {
    title: '5 days',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 153.45,
    category: 'Juice Cleanse',
  },
  {
    title: '5 days + shots',
    variationName: '8oz',
    description: '15 juices + 10 shots',
    inventory: 10,
    price: 84.64,
    category: 'Juice Cleanse',
  },
  {
    title: '5 days + shots',
    variationName: '12oz',
    description: '',
    inventory: 10,
    price: 108.1,
    category: 'Juice Cleanse',
  },
  {
    title: '5 days + shots',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 135.7,
    category: 'Juice Cleanse',
  },
  {
    title: '5 days + shots',
    variationName: '24oz',
    description: '',
    inventory: 10,
    price: 177.1,
    category: 'Juice Cleanse',
  },
  {
    title: 'Cliff Bar',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 2.5,
    category: 'Miscellaneous',
  },
  {
    title: 'Coconut Bites',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 0.6,
    category: 'Miscellaneous',
  },
  {
    title: 'Ferrero Rocher',
    variationName: 'Regular',
    description: 'CHocolate',
    inventory: 10,
    price: 0.25,
    category: 'Miscellaneous',
  },
  {
    title: 'Kind Bar',
    variationName: 'Large',
    description: '',
    inventory: 10,
    price: 2.5,
    category: 'Miscellaneous',
  },
  {
    title: 'Poland Spring Water',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 1.0,
    category: 'Miscellaneous',
  },
  {
    title: 'Rice Krispies',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 2.0,
    category: 'Miscellaneous',
  },
  {
    title: 'Sea Weed',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 2.0,
    category: 'Miscellaneous',
  },
  {
    title: 'Z Bar',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 2.0,
    category: 'Miscellaneous',
  },
  {
    title: 'Delish Quinoa salad',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 8.5,
    category: 'Salad',
  },
  {
    title: 'Tofu Chorizo Salad',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 9.0,
    category: 'Salad',
  },
  {
    title: 'Berry Excited',
    variationName: '16oz',
    description: 'Strawberry Blueberry Raspberry',
    inventory: 10,
    price: 6.0,
    category: 'Smoothies',
  },
  {
    title: 'Berry Excited',
    variationName: '20oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Smoothies',
  },
  {
    title: 'Chunky Monkey',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 7.0,
    category: 'Smoothies',
  },
  {
    title: 'Chunky Monkey',
    variationName: '20oz',
    description: '',
    inventory: 10,
    price: 9.0,
    category: 'Smoothies',
  },
  {
    title: "Einstein's Brain",
    variationName: '16oz',
    description: 'Spinach Banana PeanutButter Walnut',
    inventory: 10,
    price: 6.0,
    category: 'Smoothies',
  },
  {
    title: "Einstein's Brain",
    variationName: '20oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Smoothies',
  },
  {
    title: 'Green Breakfast',
    variationName: '16oz',
    description: 'Kale Apple Banana PeanutButter',
    inventory: 10,
    price: 6.0,
    category: 'Smoothies',
  },
  {
    title: 'Green Breakfast',
    variationName: '20oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Smoothies',
  },
  {
    title: 'Hercules',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 7.0,
    category: 'Smoothies',
  },
  {
    title: 'Hercules',
    variationName: '20oz',
    description: '',
    inventory: 10,
    price: 9.0,
    category: 'Smoothies',
  },
  {
    title: "Kale'EM",
    variationName: '16oz',
    description: 'Kale Spinach Apple Romain Lettuce Celery Pear Ginger Banana Parsley Cilantro',
    inventory: 10,
    price: 7.0,
    category: 'Smoothies',
  },
  {
    title: "Kale'EM",
    variationName: '20oz',
    description: '',
    inventory: 10,
    price: 9.0,
    category: 'Smoothies',
  },
  {
    title: 'Nutz 4 Pumpkin',
    variationName: '16oz',
    description: 'Pumpkin Almond Cashew',
    inventory: 10,
    price: 7.0,
    category: 'Smoothies',
  },
  {
    title: 'Nutz 4 Pumpkin',
    variationName: '20oz',
    description: '',
    inventory: 10,
    price: 9.0,
    category: 'Smoothies',
  },
  {
    title: 'Osaka',
    variationName: '16oz',
    description: '',
    inventory: 10,
    price: 7.0,
    category: 'Smoothies',
  },
  {
    title: 'Osaka',
    variationName: '20oz',
    description: '',
    inventory: 10,
    price: 9.0,
    category: 'Smoothies',
  },
  {
    title: 'St.Mango',
    variationName: '16oz',
    description: 'Mango Banana Yogurt',
    inventory: 10,
    price: 6.0,
    category: 'Smoothies',
  },
  {
    title: 'St.Mango',
    variationName: '20oz',
    description: '',
    inventory: 10,
    price: 8.0,
    category: 'Smoothies',
  },
  {
    title: 'Butternut Squash Soup',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 6.0,
    category: 'Soup',
  },
  {
    title: 'Lentil Soup',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 5.5,
    category: 'Soup',
  },
  {
    title: 'Spinach Soup',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 5.5,
    category: 'Soup',
  },
  {
    title: 'Emily',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 5.0,
    category: 'Vegan Tacos',
  },
  {
    title: 'Jacob',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 5.0,
    category: 'Vegan Tacos',
  },
  {
    title: 'Joe',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 6.0,
    category: 'Vegan Tacos',
  },
  {
    title: 'Lauren',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 5.0,
    category: 'Vegan Tacos',
  },
  {
    title: 'Maria',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 5.0,
    category: 'Vegan Tacos',
  },
  {
    title: 'Sofia',
    variationName: 'Regular',
    description: '',
    inventory: 10,
    price: 5.0,
    category: 'Vegan Tacos',
  },
];
